{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "KS-SQL2018;Reporting_Status",
        "connectionString": "Provider=SQLNCLI11;Data Source=KS-SQL2018;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=Reporting_Status",
        "impersonationMode": "impersonateAccount",
        "account": "KSINT\\8093AHA",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "ASSS Indikatorer",
        "isHidden": true,
        "columns": [
          {
            "name": "Barnehage",
            "dataType": "int64",
            "sourceColumn": "Barnehage",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Miljøforvaltning",
            "dataType": "int64",
            "sourceColumn": "Miljøforvaltning",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Samferdsel",
            "dataType": "int64",
            "sourceColumn": "Samferdsel",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Barnevern",
            "dataType": "int64",
            "sourceColumn": "Barnevern"
          },
          {
            "name": "Pleie og omsorg",
            "dataType": "int64",
            "sourceColumn": "Pleie og omsorg"
          },
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Byggesak",
            "dataType": "int64",
            "sourceColumn": "Byggesak"
          },
          {
            "name": "Eiendomsforvaltning",
            "dataType": "int64",
            "sourceColumn": "Eiendomsforvaltning"
          },
          {
            "name": "Kommunehelse",
            "dataType": "int64",
            "sourceColumn": "Kommunehelse"
          },
          {
            "name": "Sosiale tjenester",
            "dataType": "int64",
            "sourceColumn": "Sosiale tjenester"
          },
          {
            "name": "Grunnskole",
            "dataType": "int64",
            "sourceColumn": "Grunnskole"
          }
        ],
        "partitions": [
          {
            "name": "ASSS Indikatorer",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>149</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>184</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "SFS Kommunale veier i km per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "",
              "var lengde_komvei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(lengde_komvei, DIVIDE(innb, 10000)),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Antall km tilrettelagt for syklende som kommunen har ansvaret for per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var lengde_syklende = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde  tilrettelagt for syklende som kommunen har ansvaret for (km)\")",
              ")",
              "",
              "var innb_ant = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(lengde_syklende, DIVIDE(innb_ant, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Brutto driftsutgifter eksklusiv avskrivninger samferdsel per km (kroner)",
            "expression": [
              " ",
              "",
              "var agd10 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")   ",
              "",
              "var a590 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),  ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A590\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ") ",
              "",
              "var vei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "Return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (agd10 - a590) * 1000, ",
              "            vei",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnader til gatebelysning per lyspunkt, kommunale veier",
            "expression": [
              "",
              "var gate = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12183\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutgifter til gatebelysning langs kommunale veier og gater (1000 kr)\")",
              ")   ",
              "",
              "var lys = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11845\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lyspunkt langs kommunale veier og gater (antall)\")   ",
              ")  ",
              "",
              "RETURN (",
              "    ROUND(",
              "        DIVIDE((gate * 1000), lys),",
              "        1  ",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Drenering/overvann, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til drenering/overvann\"",
              "    )",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Trafikksikkerhet inkludert skilting og veimerking, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til trafikksikkerhet inkl skilting og vegmerking\"",
              "    )",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Renhold, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til renhold\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Vinterdrift, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til vinterdrift\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Investeringer til veidekker (asfalt) per meter vei (kroner)",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Investeringer til veidekker\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Sykefravær samferdsel (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Samferdsel (PAI)\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Veidekker, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til veidekker\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde*1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel adkomst- og GS-vei på og/eller over akseptabel standard - tilstandsgrad TG2 (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Andel adkomst- og GS-veg over akseptabelt nivå > TG2\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel gate og samlevei på og/eller over akseptabel standard - tilstandsgrad TG1 (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Andel gate og samleveg over akseptabelt nivå > TG1\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnad per meter vei for å komme over akseptabel standard (kroner)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kostnad per meter veg for å komme over akseptabel standard\"",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "BNV Netto driftsutgifter barnevernstjenester per innbygger 0-17 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] IN {\"244\", \"251\", \"252\"}),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE((ndrbv*1000), barn),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med undersøkelser i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "/* gammel kode",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Barn med undersøking  (antall)\");",
              "(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100",
              "*/",
              "",
              "var barn_und =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12286\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med undersøking  (antall)\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barn_und, pers_017) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med barneverntiltak i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\");",
              "(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100",
              "*/",
              "",
              "",
              "/* Valg mellom i løpet av året eller per 31.12 */",
              "var barn_mtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-22 år\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(    ",
              "        DIVIDE(barn_mtiltak, pers_017) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)",
            "expression": [
              "",
              "/*",
              "CALCULATE(SUM('Alle Data'[Verdi]);",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "    FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))",
              "*/",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"252 - Barnevernstiltak når barnet er plassert av barnevernet\"",
              "    ),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-22 år\")",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som er plassert i løpet av året i prosent av antall barn 0-17 år",
            "expression": [
              "",
              "",
              "var barn_017 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)], ",
              "            barn_017",
              "        ) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "/*",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Funksjon'[Dimensjonskode]);'Funksjon'[Dimensjonskode] = \"251\");",
              "FILTER(ALL(Variabel[Variabelnavn]); ",
              "Variabel[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), Funksjon[Dimensjonsnavn] = ",
              "        \"251 - Barnevernstiltak når barnet ikke er plassert av barnevernet\"",
              "    ),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\")",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak  (0-22 år)",
            "expression": [
              "",
              "/*",
              "var tiltak022 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); ",
              "'Variabel'[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\")",
              ")",
              "",
              "return DIVIDE([Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)];tiltak022)*100",
              "*/",
              "",
              "var tiltak022 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],",
              "            tiltak022",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f251) som ikke er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD10\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"251\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return DIVIDE((brbv*1000);[Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              " )",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000, ",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD10\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000); [Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              " )",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f244) med undersøkelse eller tiltak (kroner)*",
            "expression": [
              "",
              "/*",
              "var br244 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12279\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\")",
              ")",
              "",
              "return br244",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12279\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel undersøkelser gjennomført i løpet av 3 måneder (prosent)*",
            "expression": [
              "",
              "/*",
              "var und= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12280\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Undersøkingar med handsamingstid innan 3 månader (prosent)\")",
              ")",
              "",
              "return und",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12280\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Undersøkingar med handsamingstid innan 3 månader (prosent)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Sykefravær barnevern (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"PAI02\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Netto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000);[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f244 (prosent)",
            "expression": [
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto244 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"244\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto244;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto244 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"244\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto244, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f251 (prosent)",
            "expression": [
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto251 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"251\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto251;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto251 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto251, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f252 (prosent)",
            "expression": [
              "",
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto252 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto252;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto252 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto252, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med melding av innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "var melding = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12615\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (divide(melding;barn))*100",
              "*/",
              "var melding = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12615\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] =  \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(melding, barn) * 100,",
              "        1",
              "    )",
              ")",
              "    ",
              ""
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Antall barn med undersøkelse eller tiltak per årsverk (funksjon 244)*",
            "expression": [
              "",
              "/*",
              "var barn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12280\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\")",
              ")",
              "",
              "return barn",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12280\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Stillinger med fagutdanning av alle fag- og tiltaksstillinger (prosent)",
            "expression": [
              "",
              "/*",
              "var fag = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12305\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"12305\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\")",
              ")",
              "",
              "return (divide(fag;stillinger)*100)",
              "*/",
              "var fag = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(fag, stillinger) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel meldinger som går til undersøkelser (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12189\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Til undersøkelse Meldinger i alt\")",
              ")",
              "",
              "var meld= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"12189\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Meldinger i alt Meldinger i alt\")",
              ")",
              "",
              "return (divide(und;meld)*100)",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Meldingar til barnevernet (antall)\"),",
              "    FILTER(ALL(Konklusjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Til undersøkelse\"),",
              "    FILTER(ALL(Handsamingstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\")",
              ")",
              "",
              "var meld = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Meldingar til barnevernet (antall)\"),",
              "    FILTER(ALL(Handsamingstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\"),",
              "    FILTER(ALL(Konklusjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, meld) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per EM (f252) (kroner)",
            "expression": [
              "",
              "/*",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "return divide((brem*1000);antall)",
              "*/",
              "",
              "var brem = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] =",
              "        \"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\"",
              "    )",
              ")",
              "",
              "var antall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brem * 1000, antall),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 0 til 66 år",
            "expression": [
              "",
              "/*",
              "var behov1 = ",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(ALL(Tabeller[Tabellnummer]); [Tabellnummer] = \"12292\");",
              "    filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3));(behov1+behov2+behov3))",
              "*/",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "            behov1 + behov2 + behov3",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 67 år+",
            "expression": [
              "",
              "/*",
              "var behov1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3));(behov1+behov2+behov3))",
              "*/",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "            behov1 + behov2 + behov3  ",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere i institusjon som har omfattende bistandsbehov: Langtidsopphold (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold (antall)\")))*100",
              "*/",
              "var beb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere på langtidsopphold (antall)\")",
              ")",
              "",
              "",
              "var bebomf = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(bebomf, beb) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 0-66 år",
            "expression": [
              "",
              "/*",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer1*brukere1*52);(timer1*brukere1*52+brukere2*timer2*52))*100",
              "*/",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ",
              "    ROUND(",
              "        DIVIDE(",
              "            timer1 * brukere1,",
              "            timer1 * brukere1 + brukere2 * timer2",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 67 år +",
            "expression": [
              "",
              "/*",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer2*brukere2*52);(timer1*brukere1*52+brukere2*timer2*52))*100",
              "*/",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            timer2 * brukere2,",
              "            timer1 * brukere1 + brukere2 * timer2",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per innbygger 0-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return Divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000);bef)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "            bef",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per innbygger 67 år+ (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) over 67 år\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000);bef)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 67 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "            bef",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 0-66 år som er beboere på institusjon eller mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return divide((gr1+gr2);bef)*100",
              "*/",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1 + gr2, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år og eldre som mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) over 80 år Heimeteneste\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) over 80 år\")))*100",
              "*/",
              "",
              "var br80he = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var pe80 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\")",
              ")",
              " ",
              "return (",
              "    ROUND(",
              "        DIVIDE(br80he, pe80) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år+ beboer på institusjon eller i bolig med heldøgns bemanning(prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Beboere bolig m/ fast tilknyttet bemanning hele døgnet 80 år og over (antall)\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) over 80 år\")",
              ")",
              "",
              "return divide((gr1+gr2);bef)*100",
              "*/",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beboere bolig m/ fast tilknyttet bemanning hele døgnet 80 år og over (antall)\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] =\"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1 + gr2, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere på institusjon 0-66 år (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) I alt Institusjonstenester\")))*100",
              "*/",
              "var br066inst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var braltinst = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "return (",
              "   ROUND(",
              "        DIVIDE(br066inst, braltinst) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Brutto driftsutgifter per plass i institusjon (kroner)",
            "expression": [
              "",
              "/*",
              "var brutg = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"253\"; \"261\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11875\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return divide((brutg*1000);plasser)",
              "*/",
              "var brutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"253\", ",
              "        \"261\"",
              "    }),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11875\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutg * 1000, plasser),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per mottaker 0-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12003\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000);mott066)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "            mott066",
              "        ),",
              "        0",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per mottaker 67 år+ (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott67= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000);mott67)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    filter(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    filter(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\"),",
              "    filter(ALL('Variabel'[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott67= ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    filter(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "            mott67",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk i brukerrettede tjenester med fagutdanning (prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\"; ",
              "\"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"})",
              ")",
              "",
              "var gr2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11924\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11924\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Avtalte årsverk (årsverk) Administrativt personell\"; \"Avtalte årsverk (årsverk) Servicefunksjon\"})",
              ")",
              "",
              "return divide(gr1;(gr2-gr3))*100",
              "*/",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\", ",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"",
              "    })",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Administrativt personell\",",
              "        \"Servicefunksjon\"",
              "    })",
              ")",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1, gr2 - gr3) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Ressursbruksindikator. Pleie og omsorg*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Pleie og omsorg\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Sykefravær pleie og omsorg (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Pleie og omsorg (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Pleie og omsorg (PAI)\")",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Legetimer per uke per beboer i sykehjem (timer)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12293\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Legetimer per uke per beboer i sykehjem (timer)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var utv16 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utv16, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var utgutv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utgutv, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede 18 år+ i bolig med fast tilknyttet personell hele døgnet (TTU)(prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede 18 år og eldre som bor i bolig med fast tilknyttet personell hele døgnet (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter bolig med fast personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter til bolig med fast tilknyttet personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk med fagutdanning (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel årsverk med fagutdanning (TTU) (prosent)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "BNV Brutto driftsutgifter per plassert barn uten EM (f252) (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]);'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return DIVIDE(((brbv-brem)*1000);",
              "('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]-antall))",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var brem = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\"",
              "    )",
              ")",
              "",
              "var antall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Antall enslige mindreårige f252\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (brbv - brem) * 1000, ",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)] - antall",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel EM av alle plasserte barn (prosent)",
            "expression": [
              "",
              "/*",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return (DIVIDE(antall;('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]))*100)",
              "*/",
              "var antall =",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    filter(all(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "        \"Antall enslige mindreårige f252\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            antall,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med tiltak 0-5 år av barn på tiltak 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "var antall1 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\")",
              ")",
              "var antall2 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in ",
              "{\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\";",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 6-12 år\";",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 13-17 år\"})",
              ")",
              "",
              "return (DIVIDE(antall1;antall2)*100)",
              "*/",
              "var antall1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] =",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\"",
              "    )",
              ")",
              "",
              "var antall2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] IN {",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\",",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 6-12 år\",",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 13-17 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(antall1, antall2) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Ressursbruksindikator. Barnevern*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Barnevern\")",
              ")",
              "",
              "return r",
              "*/",
              "var rbi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Barnevern\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 1)",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BGS Sykefravær byggesak (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefravær Byggesak (PAI)\")",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Godkjente boligenheter per 1 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12295\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Netto endring i antall boliger (antall)\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1;(var2/1000))",
              "*/",
              "var nettoend = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12295\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Netto endring i antall boliger (antall)\") ",
              ")",
              "",
              "var befolkning = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            nettoend, ",
              "            DIVIDE(befolkning, 1000)",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Godkjent annet areal per 1 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"05939\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Fullført bruksareal til annet enn bolig\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1;(var2/1000))",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"05939\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Fullført bruksareal til annet enn bolig\") ",
              ")",
              "",
              "var var2 =",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] =  \"I alt\") ",
              ")  ",
              "",
              "var var2d1000 =",
              "DIVIDE(var2, 1000)",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, var2d1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Gjennomsnittlig saksbehandlingstid ett-trinnssøknader, 12-uker (dager)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12295\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Gjennomsnittlig saksbehandlingstid for byggesaker med 12 ukers frist (dager)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12295\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig saksbehandlingstid for byggesaker med 12 ukers frist (dager)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Saksbehandlingsgebyr for oppføring av enebolig (kroner)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12303\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Byggesaksgebyr for oppføring av enebolig (kr)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12303\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Byggesaksgebyr for oppføring av enebolig (kr)\")",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Nye søknader per 1 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ") ",
              "",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1;(var2/1000))",
              "*/",
              "",
              "var valgtkom = SELECTEDVALUE(Region[Kode])",
              "",
              "var antmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ")",
              "",
              "/* Finnes ikke i databasen per 25.10.2019 */",
              "var antdelsak = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BGS01\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Antall delingssaker\") ",
              ")",
              "",
              "var anteiersek = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12597\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Mottatte søknader om eierseksjonering (antall)\") ",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] =  \"I alt\") ",
              ")",
              "",
              "var innbd1000 =",
              "DIVIDE(innb, 1000)",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(antmott + anteiersek, innbd1000),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Tilsyn i % av nye byggesaker",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12224\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Byggesaker med tilsyn (antall)\") ",
              ")  ",
              "var var1b = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12612\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Behandlete søknader om eierseksjonering (antall)\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12224\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Behandlede byggesøknader i alt (antall)\") ",
              ") ",
              "",
              "return (divide((var1+var1b);var2))*100",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12676\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Byggesaker med tilsyn (antall)\") ",
              ")  ",
              "var var1b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12612\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Behandlete søknader om eierseksjonering (antall)\") ",
              ")  ",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12676\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Behandlede byggesøknader i alt (antall)\") ",
              ") ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1 + var1b, var2) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Antall utførte tilsyn med ikke omsøkt byggevirksomhet*",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11879\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Tilsyn i ikke omsøkte byggesaker (antall)\") ",
              ")  ",
              "",
              "return (var1)",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11879\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tilsyn i ikke omsøkte byggesaker (antall)\")",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Andel mangelfulle søknader i prosent av vedtak",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Antall mangelfulle søknader hvor det ble bedt om tilleggsdokumentasjon\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide(var1;var2))*100",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall mangelfulle søknader hvor det ble bedt om tilleggsdokumentasjon\"",
              "    ) ",
              ")  ",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\"",
              "    ) ",
              ") ",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, var2) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Brutto driftsutgifter per ferdigbehandlet byggesak (f302) (kroner)",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12611\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"302\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"2. Brutto driftsutgifter (1000 kr)\")",
              ")",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return ((divide(var1;var2))*1000)",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12611\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"302\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"2. Brutto driftsutgifter (1000 kr)\")",
              ")",
              "var var2 = ",
              "CALCULATE(sum('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\"",
              "    ) ",
              ") ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, var2) * 1000,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Andel vedtak innenfor frist (prosent)",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader med saksbehandlingstid over lovpålagt tid\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ")",
              "",
              "return (divide((var2-var1);var2))*100",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall søknader med saksbehandlingstid over lovpålagt tid\"",
              "    ) ",
              ")",
              " ",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ")",
              "return (",
              "    ROUND(",
              "        DIVIDE(var2 - var1, var2) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "BGS Totale gebyrinntekter bygge- og delesaksbehandling per f.g.vedtak (kroner)",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12299\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Beløp (1000 kr) Bygge- og delesaksbehandling Gebyrinntekter\") ",
              ")  ",
              "",
              "var var1b = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12299\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Beløp (1000 kr) Eierseksjonering Gebyrinntekter\") ",
              ")  ",
              "",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11211\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide(((var1+var1b)*1000);var2))",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12299\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Kommunal sektor'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Bygge- og delesaksbehandling\"),",
              "    FILTER(ALL('Post'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Gebyrinntekter\") ",
              ")  ",
              "",
              "var var1b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12299\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL('Kommunal sektor'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eierseksjonering\"),",
              "    FILTER(ALL('Post'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Gebyrinntekter\") ",
              ")  ",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11211\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\"",
              "    ) ",
              ")",
              "",
              "var teller =",
              "(var1 + var1b) * 1000",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(teller, var2),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Byggesak"
          },
          {
            "name": "KHT Netto driftsutgifter kommunehelsetjenesten per innbygger (kroner)",
            "expression": [
              "",
              "/*",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"232\"; \"233\"; \"241\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide((nettokom*1000);bef)",
              "*/",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] in {\"232\", \"233\", \"241\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom * 1000, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Netto driftsutgifter kommunehelsetjenesten av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "/*",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"232\"; \"233\"; \"241\"});",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12364\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return divide(nettokom;nettoalle)*100",
              "*/",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"232\", \"233\", \"241\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Dimensjonsnavn]), [Dimensjonsnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsestasjonen totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11994\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Utdanning i alt\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide(aarsverk;(bef/10000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Utdanning i alt\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsesøstre totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11994\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Helsesøster\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide(aarsverk;(bef/10000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Helsesøster\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk leger per 10 000 innbyggere (f120, f233, f241)",
            "expression": [
              "",
              "/*",
              "var aarsverk1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11996\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte legeårsverk (årsverk) Avtaleform i alt\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"120\"; \"233\"; \"241\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")",
              "",
              "return divide(aarsverk1;(bef/10000))",
              "*/",
              "var aarsverk1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11996\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte legeårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Avtaleform i alt\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"120\", \"233\", \"241\"})",
              ")",
              "",
              "var bef = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk1, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Brutto driftsutgifter (f232, f233 og f241) per innbygger (kroner)",
            "expression": [
              "",
              "/*",
              "var brkom = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"232\"; \"233\"; \"241\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")",
              "",
              "return divide((brkom*1000);person)",
              "*/",
              "var brkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"232\", \"233\", \"241\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "var person = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brkom * 1000, person),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Ledig liste-kapasitet",
            "expression": [
              "",
              "/*",
              "var kapasitet = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12005\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12005\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              ")",
              "",
              "return divide(kapasitet;pasienter)*100",
              "*/",
              "var kapasitet = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(kapasitet, pasienter) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Ledig liste-kapasitet i prosent av antall innbyggere",
            "expression": [
              "",
              "/*",
              "var kapasitet = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12005\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12005\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              "",
              ")",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "",
              "return ",
              "    (divide((kapasitet-pasienter);bef)*100)",
              "*/",
              "var kapasitet = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Kapasitet hos fastlegene (iht. liste) (antall)\")",
              ")",
              "",
              "var pasienter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Antall pasienter på fastlegeliste (antall)\")",
              "",
              ")",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(kapasitet - pasienter, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Andel nyfødte med hjembesøk innen 2 uker etter hjemkomst (prosent)",
            "expression": [
              "",
              "/*",
              "var fodte = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Hjemmebesøk nyfødte\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11820\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return divide(fodte;barn)*100",
              "*/",
              "var fodte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Hjemmebesøk nyfødte\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(fodte, barn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Sykefravær kommunehelse (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Kommunehelse (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Kommunehelse (PAI)\")",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk ergoterapeuter per 10 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var aarsverk1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRER\");",
              "    filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk ergoteraputer. Annet forebyggende helsearbeid (f233) - Annet forebyggende arbeid\")",
              ")",
              "",
              "var aarsverk2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRER\");",
              "        filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] =\"Årsverk ergoteraputer. Annet forebyggende helsearbeid (f233) - Miljørettet helsevern\")",
              ")",
              "",
              "var aarsverk3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRER\");",
              "        filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk ergoteraputer. Diagnose/ behandling, re-/habilitering (f241)\")",
              ")",
              "",
              "var aarsverk4 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRER\");",
              "        filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk ergoteraputer. Forebygging, helsestasjons- og skolehelsetjeneste (f232)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "    FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide((aarsverk1+aarsverk2+aarsverk3+aarsverk4);(bef/10000))",
              "*/",
              "var aarsverk1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Annet forebyggende helsearbeid (f233) - Annet forebyggende arbeid\"",
              "    )",
              ")",
              "",
              "var aarsverk2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Årsverk ergoteraputer. Annet forebyggende helsearbeid (f233) - Miljørettet helsevern\"",
              "    )",
              ")",
              "",
              "var aarsverk3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Diagnose/ behandling, re-/habilitering (f241)\"",
              "    )",
              ")",
              "",
              "var aarsverk4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Forebygging, helsestasjons- og skolehelsetjeneste (f232)\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "var sumaarsverk =",
              "aarsverk1 + aarsverk2 + aarsverk3 + aarsverk4",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sumaarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsestasjonen totalt per 1 000 innbyggere 0-5 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return divide(aarsverk;(bef/1000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten totalt per 1 000 innbyggere 6-20 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk totalt skolehelsetjenesten uten ledelse\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 6-20 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk;(bef/1000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk totalt skolehelsetjenesten uten ledelse\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"6-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Netto driftsutgifter forebygging, helsestasjons- og skolehelsetjeneste per innb. 0-20 år(kroner)",
            "expression": [
              "",
              "/*",
              "var nettokom = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] =\"232\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-20 år\")",
              ")",
              "",
              "return divide((nettokom*1000);bef)",
              "*/",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"232\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-22 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom * 1000, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsesykepleiere per 1 000 innbygger 0-5 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk helsesykepleiere uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk;(bef/1000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk helsesykepleiere uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk totalt på helsestasjon per innbygger 0-5 år",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return DIVIDE(aarsverk;bef)",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, bef),",
              "        4",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten per 1 000 elever barnetrinn",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk barnetrinn totalt uten ledelse. Skolehelse barnetrinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Elever i kommunale og private grunnskoler (antall) 1.-4. trinn\"; \"Elever i kommunale og private grunnskoler (antall) 5.-7. trinn\"})",
              ")",
              "",
              "return DIVIDE(aarsverk;(elev/1000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk barnetrinn totalt uten ledelse. Skolehelse barnetrinn\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"1.-4. trinn\",",
              "        \"5.-7. trinn\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(elev, 1000)),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten per 1 000 elever ungdomstrinn",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk ungdomstrinn totalt uten ledelse. Skolehelse ungdomstrinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall) 8.-10. trinn\")",
              ")",
              "",
              "return DIVIDE(aarsverk;(elev/1000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ungdomstrinn totalt uten ledelse. Skolehelse ungdomstrinn\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] =  \"8.-10. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(elev, 1000)),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelse per innbygger 16-20 år VGS",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk vg skole totalt uten ledelse. Skolehelse videregående skole\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Personer (antall) 16 år\"; \"Personer (antall) 17 år\"; \"Personer (antall) 18 år\"; \"Personer (antall) 19 år\"; \"Personer (antall) 20 år\"})",
              ")",
              "",
              "return divide(aarsverk;elev)",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk vg skole totalt uten ledelse. Skolehelse videregående skole\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonskode]), ",
              "        IF(ISERROR(VALUE([Dimensjonskode])), ",
              "            BLANK(), ",
              "            VALUE([Dimensjonskode]) >= 16 && VALUE([Dimensjonskode]) <= 20)",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, elev),",
              "        5",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk kommunale fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11995\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"FGK10\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Avtaleform i alt\")",
              ")",
              "var aarsverk241 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11995\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"241\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Avtaleform i alt\")",
              ")",
              "",
              "var aarsverkfast = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11995\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"241\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Fastlønnet\")",
              ")",
              "",
              "var aarsverkturnus = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11995\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"241\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Turnusfysioterapeut\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(((aarsverk-aarsverk241)+aarsverkfast+aarsverkturnus);(bef/10000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK10\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Avtaleform i alt\")",
              ")",
              "",
              "var aarsverk241 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"241\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Avtaleform i alt\")",
              ")",
              "",
              "var aarsverkfast = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"241\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Fastlønnet\")",
              ")",
              "",
              "var aarsverkturnus = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"241\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Turnusfysioterapeut\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "var fgk10min241 =",
              "aarsverk - aarsverk241",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            fgk10min241 + aarsverkfast + aarsverkturnus,",
              "            DIVIDE(bef, 10000)",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk private fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var aarsverk = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11995\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"FGK10\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk) Tilskudd\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(aarsverk;(bef/10000))",
              "*/",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK10\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tilskudd\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk jordmor per 10 000 fødte",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11994\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Jordmor\")",
              ")",
              "",
              "var var2= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11820\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (divide(var1;(var2/10000)))",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Jordmor\")",
              ")",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, DIVIDE(var2, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk leger per 10 000 innbyggere 0-5 år",
            "expression": [
              "",
              "/*",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11994\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Leger\")",
              ")",
              "",
              "var var2= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-5 år\")",
              ")",
              "",
              "return (divide(var1;(var2/10000)))",
              "*/",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Leger\")",
              ")",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] =\"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, DIVIDE(var2, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Spedbarnundersøkelse 8. leveuke (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt 8. leveuke\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11820\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return divide(und;barn)*100",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt 8. leveuke\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, barn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 2-3 år (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 2-3 år\")",
              ")",
              "",
              "return divide(und;(barn/2))*100",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"2-3 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, DIVIDE(barn, 2)) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 4 år (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 4 år\")",
              ")",
              "",
              "return divide(und;barn)*100",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"4 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, barn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 1. trinn (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt grunnskole 1. trinn\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 5-6 år\")",
              ")",
              "",
              "return divide(und;(barn/2))*100",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt grunnskole 1. trinn\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"5-6 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, DIVIDE(barn, 2)) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Ressursbruksindikator. Kommunehelse*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Kommunehelse\")",
              ")",
              "",
              "return r",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    filter(all('Variabel'[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Kommunehelse\")",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Målt produksjon helsestasjon",
            "expression": [
              "",
              "/*",
              "var undGrav = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12191\");",
              "    filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Antall nyinnskrevne gravide som har møtt til svangerskapskontroll (antall)\")",
              ")",
              "",
              "var undFG = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "    FILTER(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Hjemmebesøk nyfødte\")",
              ")",
              "",
              "var und8 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "    FILTER(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt 8. leveuke\")",
              ")",
              "",
              "var und23 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "    FILTER(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var und4 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11993\");",
              "    FILTER(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Barn (antall) Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var arsverkhst05= CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ÅRHOS\");",
              "    FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var vekthstprod = (21*undGrav)+(31*undFG)+(16*und8)+(16*und23)+(16*und4)",
              "",
              "return (",
              "    DIVIDE(",
              "        DIVIDE(vekthstprod;100);",
              "        arsverkhst05",
              "    )",
              ")",
              "*/",
              "var undGrav = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12191\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall nyinnskrevne gravide som har møtt til svangerskapskontroll (antall)\"",
              "    )",
              ")",
              "",
              "var undFG = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Hjemmebesøk nyfødte\")",
              ")",
              "",
              "var und8 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt 8. leveuke\")",
              ")",
              "",
              "var und23 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var und4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Dimensjonsnavn]), [Dimensjonsnavn] = \"Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var arsverkhst05 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\")",
              ")",
              "",
              "var vekthstprod = (0.21*undGrav)+(0.31*undFG)+(0.16*und8)+(0.16*und23)+(0.16*und4)",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            vekthstprod,",
              "            arsverkhst05",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Konsultasjon og sykebesøk per 1 000 innbyggere",
            "expression": [
              "",
              "/*",
              "var konsAlle = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"KPR01\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"2 konsultasjon Alle aldre Antall pasienter per 1 000 innbyggere\")",
              ")",
              "",
              "return konsAlle",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KPR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"2 konsultasjon Alle aldre Antall pasienter per 1 000 innbyggere\"",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "EIE Netto driftsutgifter eiendomsforvaltning av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "/*",
              "var nettoeien = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "/*filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"121\"; \"130\"; /*\"190\";*/ \"221\"; \"222\"; \"261\"; \"381\"; \"386\"});*/",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"FGK6a\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12364\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return divide(nettoeien;nettoalle)*100",
              "*/",
              "var nettoeien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    /*filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"121\"; \"130\"; /*\"190\";*/ \"221\"; \"222\"; \"261\"; \"381\"; \"386\"});*/",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Dimensjonsnavn]), [Dimensjonsnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettoeien, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Samlet areal på formålsbyggene i kvadratmeter per innbygger",
            "expression": [
              "",
              "/*",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"FGK6\")",
              "",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Personer (antall) I alt\")",
              ")",
              "",
              "return divide(areal;bef)",
              "*/",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(areal, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigerte brutto driftsutgifter til kommunal eiendomsforvaltning per kvadratmeter (kroner)",
            "expression": [
              "",
              "/*",
              "var korrbreien = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD4\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6a\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\")",
              ")",
              "",
              "return divide((korrbreien*1000);areal)",
              "*/",
              "var korrbreien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6a\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(korrbreien * 1000, areal),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigerte brutto driftsutgifter eksklusiv avskrivninger per kvadratmeter eiet bygg (kroner)",
            "expression": [
              "",
              "/*",
              "var brutto = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD4\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6a\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var avskr = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"A590\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6a\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var leie = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"A190\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6a\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((brutto-(leie+avskr));areal)*1000",
              "*/",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var avskr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var leie = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A190\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var leieavs =",
              "leie + avskr",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto - leieavs, areal) * 1000,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til renholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "/*",
              "var renhold = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12047\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD38\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((renhold*1000);areal)",
              "*/",
              "var renhold = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12047\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD38\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(renhold * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigert brutto driftsutgifter til kommunal forvaltning av eiendommer per kvadratmeter (kroner)",
            "expression": [
              "",
              "/*",
              "var korrbreien = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD4\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"121\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Areal totalt\")",
              ")",
              "",
              "return divide((korrbreien*1000);areal)",
              "*/",
              "var korrbreien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"121\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(korrbreien * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til driftsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "/*",
              "var drift = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12047\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD39\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((drift*1000);areal)",
              "*/",
              "var drift = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12047\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD39\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(drift * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til vedlikeholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "/*",
              "var ved = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12047\");",
              "filter(all('Alle Data'[Artsgruppekode]); 'Alle Data'[Artsgruppekode]=\"AGD36\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "",
              "return divide((ved*1000);areal)",
              "*/",
              "var ved = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12047\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD36\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              "    ",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ved * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Sykefravær eiendomsforvaltning (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Eiendomsforvaltning i Alt (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefravær Eiendomsforvaltning i Alt (PAI)\")",
              ")",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Samlet energibruk i kommunal eiendomsforvaltning kWh/m2*",
            "expression": [
              "",
              "/*",
              "var energi = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12150\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"FGK6\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Energibruk (MWh)\")",
              ")",
              "var areal = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11906\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode] = \"FGK6\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Areal (m2) Eid areal\")",
              ")",
              "return DIVIDE((energi*1000);areal)",
              "*/",
              "var energi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12150\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Energibruk (MWh)\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Dimensjonsnavn]), [Dimensjonsnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(energi * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "SFS Brutto investeringsutgifter til kommunale veier og gater per innbygger (kroner)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11816\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto investeringsutgifter til kommunale veier og gater per innbygger (kr)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "EIE Snitt årlig investering per innbygger 2015-2018 (2018-kroner byggekostnadsindeksen boligblokker)",
            "expression": [
              "",
              "/*",
              "var aar1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]);'Funksjon Kostra'[Funksjonskode]= \"FGK6\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGI5\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2015)",
              ")",
              "",
              "var aar2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode]= \"FGK6\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGI5\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2016)",
              ")",
              "",
              "var aar3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode]= \"FGK6\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGI5\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2017)",
              ")",
              "",
              "var aar4 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12559\");",
              "FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\");",
              "filter(all('Alle Data'[Funksjonskode]); 'Alle Data'[Funksjonskode]= \"FGK6\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGI5\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2018)",
              ")",
              "",
              "var bef1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Personer (antall) I alt\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2015)",
              ")",
              "",
              "var bef2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Personer (antall) I alt\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2016)",
              ")",
              "var bef3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Personer (antall) I alt\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2017)",
              ")",
              "",
              "var bef4 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Personer (antall) I alt\");",
              "FILTER(ALL('År'[År]); 'År'[År]=2018)",
              ")",
              "",
              "return ((((aar1*1,08847497089639)/bef1)+((aar2*1,06310403638431)/bef2)+",
              "((aar3*1,03429203539823)/bef3)+((aar4*1)/bef4))/4)*1000",
              "*/",
              "var aar1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = 2015)",
              ")",
              "",
              "var aar2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] =2016)",
              ")",
              "",
              "var aar3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] =\"AGI5\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = 2017)",
              ")",
              "",
              "var aar4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = 2018)",
              ")",
              "",
              "var bef1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = 2015)",
              ")",
              "",
              "var bef2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = 2016)",
              ")",
              "var bef3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = 2017)",
              ")",
              "",
              "var bef4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = 2018)",
              ")",
              "",
              "var aar1bef1 =",
              "DIVIDE(aar1 * 1.08847497089639, bef1)",
              "",
              "var aar2bef2 =",
              "DIVIDE(aar2 * 1.06310403638431, bef2)",
              "",
              "var aar3bef3 =",
              "DIVIDE(aar3 * 1.03429203539823, bef3)",
              "",
              "var aar4bef4 =",
              "DIVIDE(aar4, bef4)",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aar1bef1 + aar2bef2 + aar3bef3 + aar4bef4, 4) * 1000,",
              "        1",
              "    )",
              ")",
              "",
              "/*Husk at dette må endres!*/",
              "/*Koden BØR også justeres! - */"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "SOS Netto driftsutgifter til sosialtjenesten(f242/f243/f273/f276/f281) pr innbygger 18-66 år(kroner)",
            "expression": [
              "",
              "/*",
              "var ndrsos = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"242\"; \"243\"; \"273\"; \"276\"; \"281\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndrsos*1000);person)",
              "*/",
              "var ndrsos = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"242\", \"243\", \"273\", \"276\", \"281\"})",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndrsos * 1000, [SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter til ytelse til livsopphold (f281) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var ndr281 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"281\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndr281*1000);person)",
              "*/",
              "var ndr281 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"281\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var person = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr281 * 1000,[SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter tilbud personer med rusproblemer (f243) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var ndr243 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"243\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide((ndr243*1000);person)",
              "*/",
              "var ndr243 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"243\")",
              ")",
              "var person = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr243 * 1000, [SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere av innbyggere 18-66 år (prosent)",
            "expression": [
              "",
              "/*",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")",
              "var bef= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 18-66 år\")",
              ")",
              "",
              "return divide(sosmott;bef)*100",
              "*/",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmott, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere 18-24 år av innbyggere 18-24 år (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Sosialhjelpsmottakere 18-24 år (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 18-24 år\")))*100",
              "*/",
              "",
              "var sosmot = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere 18-24 år (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-24 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmot, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere 25-66 år av innbyggere 25-66 år (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Sosialhjelpsmottakere 25-66 år (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 25-66 år\")))*100",
              "*/",
              "var sosmot = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere 25-66 år (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"25-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmot, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall mottakere av kvalifiseringsstønad (f276) per 1 000 innbyggere 18-66 år",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Deltakere (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 18-66 år\")/1000))",
              "*/",
              "var delt = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12160\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Deltakere (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(delt, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønad (bidrag+lån) per sosialhjelpsmottaker (kroner)",
            "expression": [
              "",
              "/*",
              "var stonad = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\"); ",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Samlet stønadssum (bidrag + lån)  (kr)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(stonad;sosmott)",
              "*/",
              "var stonad = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Samlet stønadssum (bidrag + lån)  (kr)\") ",
              ")",
              "",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(stonad, sosmott),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel med sosialhjelp som hovedinntekt/mottak i 6 mnd eller mer (alle mottakere/aldre) (prosent)",
            "expression": [
              "",
              "/*",
              "var langtid= CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12213\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere 6 måneder eller mer og sosialhjelp som hovedinntekt  (antall)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(langtid;sosmott)*100",
              "*/",
              "var langtid = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere 6 måneder eller mer og sosialhjelp som hovedinntekt  (antall)\"",
              "    ) ",
              ") ",
              "",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(langtid, sosmott) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønadslengde sosialhjelpsmottakere 18-24 år. Gjennomsnittlig antall måneder per år*",
            "expression": [
              "",
              "/*",
              "var lengde = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadstid 18-24 år (antall)\")",
              ")",
              "",
              "return lengde",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Gjennomsnittlig stønadstid 18-24 år (antall)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Etter KVP: Andel deltakere som gikk til arbeid/skole/utdanning (prosent)*",
            "expression": [
              "",
              "/*",
              "var kvp = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"STKVP\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Etter KVP: Andel deltakere som gikk arbeid/skole/utdanning\")",
              ")",
              "",
              "return kvp",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KVP01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Etter KVP: Andel deltakere som gikk arbeid/skole/utdanning\"",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Sykefravær sosiale tjenester (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Sosiale tjenester (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefravær Sosiale tjenester (PAI)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere som forsørger barn under 18 år (prosent)",
            "expression": [
              "",
              "/*",
              "var langtid= CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12219\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\") ",
              ") ",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")  ",
              "return divide(langtid;sosmott)*100",
              "*/",
              "var langtid = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\"",
              "    ) ",
              ") ",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(langtid, sosmott) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønadslengde mottakere med sosialhjelp som hovedinntektskilde. Snitt måneder per år*",
            "expression": [
              "",
              "/*",
              "var lengde = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12213\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\")",
              ")",
              "",
              "return lengde",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Ressursbruksindikator. Sosiale tjenester*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Sosiale tjenester\")",
              ")",
              "",
              "return r",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Sosiale tjenester\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall sosialhjelpsmottakere som forsørger barn under 18 år",
            "expression": [
              "",
              "/*",
              "var langtid= CALCULATE(sum('Alle Data'[Verdi]); ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12219\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\") ",
              ") ",
              "  ",
              "return (langtid)",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\"",
              "    ) ",
              ") "
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall sosialhjelpsmottakere av innbyggere 18-66 år",
            "expression": [
              "",
              "/*",
              "var sosmott = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12219\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")",
              "",
              "return sosmott",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12219\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Sosialhjelpsmottakere med sosialhjelp som viktigste kilde til livsopphold (antall)",
            "expression": [
              "",
              "/*",
              "var sosv = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sosialhjelpsmottakere med sosialhjelp som viktigste kilde til livsopphold (antall)\")",
              ")",
              "",
              "return sosv",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12203\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere med sosialhjelp som viktigste kilde til livsopphold (antall)\"",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Gjennomsnittlig stønadslengde med sosialhjelp som hovedinntekt (måneder)",
            "expression": [
              "",
              "/*",
              "var soslg = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\")",
              ")",
              "",
              "return soslg",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = ",
              "        \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\"",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Brutto driftsutgifter til sosialtjenesten (f242/f243/f273/f276/f281) (kroner)",
            "expression": [
              "",
              "/*",
              "var bdrsos = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"242\"; \"243\"; \"273\"; \"276\"; \"281\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return bdrsos",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"242\", \"243\", \"273\", \"276\", \"281\"})",
              ")",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter til sosialtjenesten (f242/f243/f273/f276/f281) (kroner)",
            "expression": [
              "",
              "/*",
              "var ndrsos = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"242\"; \"243\"; \"273\"; \"276\"; \"281\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return ndrsos",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"242\", \"243\", \"273\", \"276\", \"281\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall innbyggere 18-66",
            "expression": [
              "",
              "\tCALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"18-66 år\")",
              ")",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "BHG Netto driftsutgifter barnehager per innbygger 1-5 år (kroner)",
            "expression": [
              "",
              "/*",
              "var nettobhg = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"201\"; \"211\"; \"221\"});",
              "filter(ALL('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 1-5 år\")",
              ")",
              "",
              "return (divide((nettobhg*1000);bef))",
              "*/",
              "var nettobhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"201\", \"211\", \"221\"})",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"1-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettobhg * 1000, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Netto driftsutgifter barnehager av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "/*",
              "var nettobhg = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"201\"; \"211\"; \"221\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12364\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn] = \"Netto driftsutgifter totalt Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(nettobhg;nettoalle)*100)",
              "*/",
              "var nettobhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {\"201\", \"211\", \"221\"})",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Dimensjonsnavn]), [Dimensjonsnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettobhg, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Andel minoritetsspråklige barn i barnehage i forhold til innvandrerbarn (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Minoritetsspråklige barn (antall)\");(",
              "CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Innvandrerbarn (antall)\")))*100",
              "*/",
              "",
              "var minbarn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Minoritetsspråklige barn (antall)\")",
              ")",
              "",
              "var innbarn =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innvandrerbarn (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(minbarn, innbarn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-2 år i barnehage av innbyggere 1-2 år (prosent)",
            "expression": [
              "",
              "/*",
              "var barnbhg12 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 1-2 år Alle eierforhold Alle oppholdskategorier\")",
              ")",
              "",
              "var barn12 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Personer (antall) 1-2 år\");",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\")",
              ")",
              "",
              "return (divide(barnbhg12;barn12)*100)",
              "*/",
              "var barnbhg12 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"1-2 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn12 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"1-2 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnbhg12, barn12) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 3-5 år i barnehage av innbyggere 3-5 år (prosent)",
            "expression": [
              "",
              "/*",
              "var barnbhg35 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 3-5 år Alle eierforhold Alle oppholdskategorier\")",
              ")",
              "",
              "var barn35 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Personer (antall) 3-5 år\");",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11805\")",
              ")",
              "",
              "return (divide(barnbhg35;barn35)*100)",
              "*/",
              "var barnbhg35 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"3-5 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn35 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"3-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnbhg35, barn35) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-5 år i barnehage av innbyggere 1-5 år (prosent)",
            "expression": [
              "",
              "/*",
              "divide(CALCULATE(sum('Alle Data'[Verdi]); 'Variabel'[Variabelnavn]=\"Barn i barnehage 1-5 år\");",
              "(CALCULATE(sum('Alle Data'[Verdi]); Variabel[Variabelnavn]=\"Personer (antall) 1-5 år\")))*100",
              "*/",
              "var bhgbarn15 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\")",
              ")",
              "",
              "var allebarn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"1-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(bhgbarn15, allebarn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Minoritetsspråklige barn i barnehage av alle barnehagebarn 1-5 år (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Minoritetsspråklige barn (antall)\");(",
              "CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Barn i barnehage 1-5 år\")))*100",
              "*/",
              "var minorbhgbarn15 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Minoritetsspråklige barn (antall)\")",
              ")",
              "",
              "var bhgbarn15 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(minorbhgbarn15, bhgbarn15) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn i kommunale barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "/*",
              "var barnkom = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 0-6 år Kommune Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Barn i barnehage (antall) 0-6 år Alle eierforhold Alle oppholdskategorier\");",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12056\")",
              ")",
              "",
              "return (divide(barnkom;barnbhg)*100)",
              "*/",
              "var barnkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnkom, barnbhg) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn i private barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "/*",
              "var barnkom = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 0-6 år Privat Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Barn i barnehage (antall) 0-6 år Alle eierforhold Alle oppholdskategorier\");",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12056\")",
              ")",
              "",
              "return (divide(barnkom;barnbhg)*100)",
              "*/",
              "var barnkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Privat\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnkom, barnbhg) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Andel menn av grunnbemanningen barnehager (prosent)",
            "expression": [
              "",
              "/*",
              "var ansatte = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12129\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Kvinne Annen grunnbemanning\"; \"Ansatte (antall) Alle eierforhold Kvinne Pedagogisk leder\"; \"Ansatte (antall) Alle eierforhold Kvinne Styrer\"; \"Ansatte (antall) Alle eierforhold Mann Annen grunnbemanning\"; \"Ansatte (antall) Alle eierforhold Mann Pedagogisk leder\"; \"Ansatte (antall) Alle eierforhold Mann Styrer\"})",
              ")",
              "",
              "var menn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12129\");",
              "filter(ALL('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Mann Annen grunnbemanning\"; \"Ansatte (antall) Alle eierforhold Mann Pedagogisk leder\"; \"Ansatte (antall) Alle eierforhold Mann Styrer\"})",
              ")",
              "",
              "return (divide(menn;ansatte)*100)",
              "*/",
              "var ansatte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Stillingstype[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Annen grunnbemanning\",",
              "        \"Pedagogisk leder\",",
              "        \"Styrer\"",
              "    })",
              ")",
              "",
              "var menn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Mann\"),",
              "    FILTER(ALL(Stillingstype[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Annen grunnbemanning\",",
              "        \"Pedagogisk leder\",",
              "        \"Styrer\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(menn, ansatte) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn ekskl. minoritetsspråklige med ekstra ressurser av alle barn i kom. barnehager (prosent)*",
            "expression": [
              "",
              "/*",
              "var barnekstra = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12562\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Andel barn, eksklusive minoritetsspråklige, som får ekstra ressurser, i forhold til alle barn i kommunale barnehager (prosent)\")",
              ")",
              "",
              "return barnekstra",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12562\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel barn, eksklusive minoritetsspråklige, som får ekstra ressurser, i forhold til alle barn i kommunale barnehager (prosent)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Korrigerte brutto driftsutgifter f201 per korrigert oppholdstime i kommunale barnehage (kroner)",
            "expression": [
              "",
              "/*",
              "var kbr201 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD4\");",
              "FILTER(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"201\")",
              ")",
              "var kopph = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12216\");",
              "filter(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Korrigerte oppholdstimer (timer) Kommune\")",
              ")",
              "return (divide((kbr201*1000);kopph))",
              "*/",
              "var kbr201 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\")",
              ")",
              "",
              "var kopph = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12216\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Korrigerte oppholdstimer (timer)\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kommune\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(kbr201 * 1000, kopph),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per ansatt kommunale barnehager*",
            "expression": [
              "",
              "/*",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BPA\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn per ansatt i barnehagen (bemanningstetthet) Kommunal\")",
              ")",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn per ansatt i barnehagen (bemanningstetthet) Kommunal\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per ansatt private barnehager*",
            "expression": [
              "",
              "/*",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BPA\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn per ansatt i barnehagen (bemanningstetthet) Privat\")",
              ")",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn per ansatt i barnehagen (bemanningstetthet) Privat\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Ansatte med barnehagelærerutdanning/annen pedagogisk utdanning av alle ansatte (prosent)",
            "expression": [
              "",
              "/*",
              "var utd = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"09345\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Kommune\"; \"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Privat\";",
              "\"Ansatte Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Fylkeskommune/stat\"; \"Ansatte Barnehagelærer Fylkeskommune/stat\"; \"Ansatte Barnehagelærer Kommune\"; \"Ansatte Barnehagelærer Privat\"})",
              ")",
              "",
              "var ansatte = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12129\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Ansatte (antall) Alle eierforhold Kvinne Alle stillingstyper\"; \"Ansatte (antall) Alle eierforhold Mann Alle stillingstyper\"})",
              ")",
              "",
              "return (divide(utd;ansatte)*100)",
              "*/",
              "var utd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"09345\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Fylkeskommune/stat\",",
              "        \"Kommune\",",
              "        \"Privat\"",
              "    }),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Barnehagelærer\",",
              "        \"Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder\"",
              "    })",
              ")",
              "",
              "var ansatte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] IN  {",
              "        \"Kvinne\",",
              "        \"Mann\"",
              "    }),",
              "    FILTER(ALL(Stillingstype[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle stillingstyper\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(utd, ansatte) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Sykefravær barnehager (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Barnehage (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefravær Barnehage (PAI)\")",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Brukertilfredshet barnehager (snitt skår)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"FUB\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Foreldreundersøkelsen: Tilfredshet\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Foreldreundersøkelsen: Tilfredshet\")",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Ressursbruksindikator. Barnehager*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Barnehager\")",
              ")",
              "",
              "return r",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Barnehager\")",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-5 år i barnehage (antall)",
            "expression": [
              "",
              "/*",
              "var b = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage 1-5 år\")",
              ")",
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall) 0 år Alle eierforhold Alle oppholdskategorier\")",
              ")",
              "",
              "",
              "return b + a",
              "*/",
              "var b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage 1-5 år\")",
              ")",
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 år\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    a + b",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barnehagelærere i forhold til grunnbemanning (prosent)",
            "expression": [
              " ",
              "/*",
              "var bla = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Andel barnehagelærere i forhold til grunnbemanning (prosent)\")",
              ")",
              "",
              "return bla",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12562\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel barnehagelærere i forhold til grunnbemanning (prosent)\"",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per barnehagelærer kommunale barnehager",
            "expression": [
              "",
              "/*",
              "var bhg = ",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "    filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12436\");",
              "    filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {",
              "        \"Årsverk Kommune Barnehagelærer Grunnbemanning\";",
              "        \"Årsverk Kommune Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder Grunnbemanning\"",
              "    })",
              ")",
              " ",
              "/*var barnbhg = CALCULATE(sum('Alle Data'[Verdi]);*/",
              "/*filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\\\"12216\\\");*/",
              "/*filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\\\"Barn i barnehage korrigert for alder (antall) Kommune\\\")*/",
              "",
              "var barn1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "    filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {",
              "        \"Barn i barnehage (antall) 0 år Kommune Alle oppholdskategorier\";",
              "        \"Barn i barnehage (antall) 1-2 år Kommune Alle oppholdskategorier\"",
              "    })",
              ")",
              "",
              "var barn2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "    filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12056\");",
              "    filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {",
              "        \"Barn i barnehage (antall) 6 år Kommune Alle oppholdskategorier\"; ",
              "        \"Barn i barnehage (antall) 3-5 år Kommune Alle oppholdskategorier\"",
              "    })",
              ")",
              "",
              "return (divide(((barn1*2)+(barn2*1)); bhg))",
              "",
              "/*Barn er korrigert ut fra endret vekt - dette er ikke korrigert hos SSB*/",
              "/*27.3.2019 Laila */",
              "*/",
              "var bhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12436\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk\"),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kommune\"),",
              "    FILTER(ALL(Stillingstype[Dimensjonsnavn]), [Dimensjonsnavn] = \"Grunnbemanning\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Barnehagelærer\", ",
              "        \"Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder\"",
              "    })",
              ")",
              " ",
              "/*var barnbhg = CALCULATE(sum('Alle Data'[Verdi]);*/",
              "/*filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\\\"12216\\\");*/",
              "/*filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\\\"Barn i barnehage korrigert for alder (antall) Kommune\\\")*/",
              "",
              "var barn1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"0 år\", ",
              "        \"1-2 år\"",
              "    }),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"3-5 år\",",
              "        \"6 år\"",
              "    }),",
              "    FILTER(ALL(Eierforhold[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE((barn1 * 2) + barn2, bhg),",
              "        1 ",
              "    )",
              ")",
              "",
              "/*Barn er korrigert ut fra endret vekt - dette er ikke korrigert hos SSB*/",
              "/*27.3.2019 Laila */"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "GRS Netto driftsutgifter grunnskole (f202) per elev (kroner)",
            "expression": [
              "",
              "/*",
              "var ndr202 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"202\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11977\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return divide((ndr202*1000);elev)",
              "*/",
              "var ndr202 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"202\")",
              ")",
              "",
              "var elev = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11977\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr202 * 1000, elev),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Gruppestørrelse (antall)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elevtimer (antall) Elever alle trinn\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Lærertimer minus morsmål og finsk (antall) Elever alle trinn\")))",
              "*/",
              "var etalle =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12285\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevtimer (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "var ltmmf =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12285\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærertimer minus morsmål og finsk (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(etalle, ltmmf),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler som får spesialundervisning (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) Elever alle trinn\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler (antall) Elever alle trinn\")))*100",
              "*/",
              "",
              "var elspes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "var elall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(elspes, elall) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Årstimer til spesialundervisning per elev med spesialundervisning (antall)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Årstimer til spesialundervisning, kommunale og private grunnskoler (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) Elever alle trinn\")))",
              "*/",
              "var aartspes =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11974\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årstimer til spesialundervisning, kommunale og private grunnskoler (antall)\"",
              "    )",
              ")",
              "",
              "var antelevspes =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aartspes, antelevspes),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever med direkte overgang fra vg1 til vg2 (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elever som var registrert i videregående opplæring vg2 samme år som avsluttet vg1 (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Elever som avsluttet vg1 (antall)\")))*100",
              "*/",
              "var a =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12236\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever som var registrert i videregående opplæring vg2 samme år som avsluttet vg1 (antall)\"",
              "    )",
              ")",
              "",
              "var b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12236\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever som avsluttet vg1 (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, b) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 5. trinn, snitt andel nivå 2-3 (prosent)*",
            "expression": [
              "",
              "/*",
              "var les = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP5\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 3\"; \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 2\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP5\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Regning Mestringsnivå 3\"; \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 2\"})",
              ")",
              "",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP5\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 3\"; \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 2\"})",
              ")",
              "",
              "return divide((les+regn+eng);3)",
              "*/",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 3\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 3\"",
              "    })",
              ")",
              "",
              "var eng = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 3\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(les + regn + eng, 3),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 8. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "/*",
              "var les = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP8\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 3\"; \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 4\"; \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 5\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP8\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Regning Mestringsnivå 3\"; \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 4\"; \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 5\" })",
              ")",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP8\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 3\"; \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 4\"; \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 5\" })",
              ")",
              "",
              "return divide((eng + les + regn);3)",
              "*/",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 5\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "var eng = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(les + regn + eng, 3),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 9. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "/*",
              "var les = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP9\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 3\"; \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 4\"; \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 5\"})",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"NP9\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in {\"Nasjonale prøver Trinn 9: Regning Mestringsnivå 3\"; \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 4\"; \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 5\" })",
              ")",
              "",
              "return divide((les + regn);2)",
              "*/",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 5\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(les + regn, 2),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Sykefravær grunnskole (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Grunnskole (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Grunnskole (PAI)\")",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Eksamen snitt engelsk, regning og norsk*",
            "expression": [
              "",
              "/*",
              "var eng = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ER\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Engelsk skriftlig eksamen\")",
              ")",
              "var regn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ER\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Matematikk skriftlig eksamen\")",
              ")",
              "var n1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ER\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Norsk hovedmål skriftlig eksamen\")",
              ")",
              "",
              "var n2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ER\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Norsk sidemål skriftlig eksamen\")",
              ")",
              "return (((n1+n2)/2)+eng+regn)/3",
              "*/",
              "var eng = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Engelsk skriftlig eksamen\")",
              ")",
              "var regn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Matematikk skriftlig eksamen\")",
              ")",
              "var n1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Norsk hovedmål skriftlig eksamen\")",
              ")",
              "",
              "var n2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Norsk sidemål skriftlig eksamen\")",
              ")",
              "",
              "var n1n2d2 =",
              "DIVIDE(n1 + n2, 2)",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(n1n2d2 + eng + regn, 3),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Vurdering for læring (snitt skår)*",
            "expression": [
              "",
              "/*",
              "var a= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"EU\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Elevundersøkelsen Trinn 10: Vurdering for læring\")",
              "",
              ")",
              "var b = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"EU\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Elevundersøkelsen Trinn 7: Vurdering for læring\")",
              ")",
              "",
              "return divide((a+b);2)",
              "*/",
              "var a = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS05\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevundersøkelsen Trinn 10: Vurdering for læring\")",
              "",
              ")",
              "var b = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS05\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevundersøkelsen Trinn 7: Vurdering for læring\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a + b, 2),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (prosent)",
            "expression": [
              "",
              "/*",
              "var saer = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12234\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "=\"Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (antall)\")",
              ")",
              "var alleelev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12234\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "=\"Elever i kommunale og private grunnskoler (antall)\")",
              ")",
              "",
              "return DIVIDE(saer;alleelev)*100",
              "*/",
              "var saer = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12234\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (antall)\"",
              "    )",
              ")",
              "",
              "var alleelev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12234\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(saer, alleelev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Netto driftsutgifter skoleskyss (f223) per elev (kroner)",
            "expression": [
              "",
              "/*",
              "var ndr223 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"223\");",
              "filter(all('Variabel'[Variabelnavn]); Variabel[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"11977\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return divide((ndr223*1000);elev)",
              "*/",
              "var ndr223 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"223\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11977\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr223 * 1000, elev),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 40 år og yngre (prosent)",
            "expression": [
              "",
              "/*",
              "var l40 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 40 år og yngre\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l40;alle))*100)",
              "*/",
              "var l40 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"40 år og yngre\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l40, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 41 - 49 år (prosent)",
            "expression": [
              "",
              "/*",
              "var l4049 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 41 til 49 år\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l4049;alle))*100)",
              "*/",
              "var l4049 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"41 til 49 år\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l4049, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 50 - 59 år (prosent)",
            "expression": [
              "",
              "/*",
              "var l5059 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 50 til 59 år\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l5059;alle))*100)",
              "*/",
              "var l5059 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"50 til 59 år\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l5059, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 60 år og eldre (prosent)",
            "expression": [
              "",
              "/*",
              "var l60 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn 60 år og eldre\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12282\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Alle aldersgrupper\")",
              ")",
              "",
              "return ((divide(l60;alle))*100)",
              "*/",
              "var l60 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"60 år og eldre\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l60, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Gjennomsnittlig antall elever per kommunale skole",
            "expression": [
              "",
              "/*",
              "var elever = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11971\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale skoler (antall)\")",
              ")",
              "",
              "var skoler = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11971\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Kommunale grunnskoler (antall)\")",
              ")",
              "",
              "return (divide(elever;skoler))",
              "*/",
              "var elever = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11971\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale skoler (antall)\")",
              ")",
              "",
              "var skoler = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11971\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Kommunale grunnskoler (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(elever, skoler),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 1.-4. trinn (prosent)",
            "expression": [
              "",
              "/*",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 1.-4. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 1.-4. trinn\")",
              ")",
              "",
              "return ((divide(spes;elev))*100)",
              "*/",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"1.-4. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"1.-4. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 5.-7. trinn (prosent)",
            "expression": [
              "",
              "/*",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 5.-7. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 5.-7. trinn\")",
              ")",
              "",
              "return ((divide(spes;elev))*100)",
              "*/",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"5.-7. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"5.-7. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 8.-10. trinn (prosent)",
            "expression": [
              "",
              "/*",
              "var spes = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall) 8.-10. trinn\")",
              ")",
              "",
              "var elev = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12222\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Elever i kommunale og private grunnskoler (antall) 8.-10. trinn\")",
              ")",
              "",
              "return ((divide(spes;elev))*100)",
              "*/",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"8.-10. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"8.-10. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Ressursbruksindikator. Grunnskole*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Grunnskole\")",
              ")",
              "",
              "return r",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Grunnskole\")",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Ressursbruksindikator. Grunnskole F202*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Grunnskole F202\")",
              ")",
              "",
              "return r",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Grunnskole F202\")",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Antall assistentårsverk per hundre lærerårsverk*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RGS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Antall assistentårsverk per hundre lærerårsverk\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS06\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Antall assistentårsverk per hundre lærerårsverk\")",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med universitets-/høgskoleutdanning med pedagogisk utdanning (prosent)",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Universitets-/høgskoleutdanning, med pedagogisk utdanning\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Kompetanse i alt\")",
              ")",
              "",
              "return ((divide(a;alle))*100)",
              "*/",
              "var unihogutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Universitets-/høgskoleutdanning, med pedagogisk utdanning\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(unihogutd, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med universitets-/høgskoleutdanning uten pedagogisk utdanning (prosent)",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Universitets-/høgskoleutdanning, uten pedagogisk utdanning\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Kompetanse i alt\")",
              ")",
              "",
              "return ((divide(a;alle))*100)",
              "*/",
              "var unihogutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Universitets-/høgskoleutdanning, uten pedagogisk utdanning\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(unihogutd, alle) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med videregående utdanning eller lavere (prosent)",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Videregående utdanning eller lavere\")",
              ")",
              "",
              "var alle = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12247\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] ",
              "= \"Lærere (antall) Begge kjønn Kompetanse i alt\")",
              ")",
              "",
              "return ((divide(a;alle))*100)",
              "*/",
              "var vgsutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Videregående utdanning eller lavere\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Dimensjonsnavn]), [Dimensjonsnavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(vgsutd, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "TST Kommunenavn test",
            "expression": [
              "",
              "var kode = SELECTEDVALUE(Region[Kode])",
              "",
              "return (",
              "    LOOKUPVALUE(Region[Navn], Region[Kode], kode)",
              ")"
            ]
          },
          {
            "name": "TST Konstant",
            "expression": [
              "",
              "/*CALCULATE(SUMX(FILTER(ALL('Alle Data'); [Kode] = \"0106\"); 'Alle Data'[Verdi]))*/",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(",
              "        SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "        FILTER(ALL(Region[Navn]), [Navn] = \"Fredrikstad\"),",
              "        FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "        FILTER(ALL('År'[År]), [År] = 2018)",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST Bruk med konstant",
            "expression": [
              "",
              "",
              "[TST Konstant] - [BHG Barn 1-5 år i barnehage (antall)]"
            ]
          },
          {
            "name": "TST BHG Netto driftsutgifter eksklusiv avskrivninger",
            "expression": [
              "",
              "",
              "var f201nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f201avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "var f211nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f211avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "var f221nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f221avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "return (",
              "    (f201nd + f211nd + f221nd) - (f201avs + f211avs + f221avs)",
              ")"
            ]
          },
          {
            "name": "TST BHG Netto driftsutgifter eksklusiv avskrivninger per innbygger",
            "expression": [
              "",
              "",
              "var innbtall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggertall per 1. juli\")",
              ")",
              "",
              "return(",
              "    ROUND(",
              "        DIVIDE([TST BHG Netto driftsutgifter eksklusiv avskrivninger] * 1000, innbtall),",
              "        0",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Beregnet utgiftsbehov",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var indinnb25 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks innb. 2-5 år\")",
              ")",
              "",
              "var indbukst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks barn 1 år utan kontant-støtte\")",
              ")",
              "",
              "var indinnbhutd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks innb. m. høgare ut-danning\")",
              ")",
              "",
              "var vektinnb25 =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innb 2-5 år\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var vektbarn1utkst =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innb 1 år u/kont\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var vektinnbmhutd =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere med høyere utdanning\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var innb25mvekt =",
              "indinnb25 * vektinnb25",
              "",
              "var innbukstmvekt = ",
              "indbukst * vektbarn1utkst",
              "",
              "var innbhutdmvekt = ",
              "indinnbhutd * vektinnbmhutd",
              "",
              "return (",
              "    ROUND(",
              "        innb25mvekt + innbukstmvekt + innbhutdmvekt,",
              "        4",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Beregnet utgiftsbehov korrigert for forskjellene i inntektssystemet",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var valgte_kom = SELECTEDVALUE(Region[Kode])",
              "",
              "var ndriutgeavslandet = ",
              "[Netto driftsutgifter eksklusiv avskrivninger per innbygger landet]",
              "",
              "var indinnb25 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks innb. 2-5 år\")",
              ") ",
              "",
              "",
              "var vktinnb25 =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innb 2-5 år\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var indbukst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks barn 1 år utan kontant-støtte\")",
              ")",
              "",
              "var vktbarn1utkst =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innb 1 år u/kont\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var indinnbhutd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Indeks innb. m. høgare ut-danning\")",
              ")",
              "",
              "var vktinnbmhutd =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO03\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere med høyere utdanning\"),",
              "        FILTER(ALL('Tjenesteområde'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Barnehage\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var innb25 = ",
              "(indinnb25 - 1) * vktinnb25 * [Netto driftsutgifter eksklusiv avskrivninger per innbygger landet]",
              "",
              "var bukst = ",
              "(indbukst - 1) * vktbarn1utkst * [Netto driftsutgifter eksklusiv avskrivninger per innbygger landet]",
              "",
              "var innbhutd = ",
              "(indinnbhutd - 1) * vktinnbmhutd * [Netto driftsutgifter eksklusiv avskrivninger per innbygger landet]",
              "",
              "return (",
              "    ROUND(",
              "        [Netto driftsutgifter eksklusiv avskrivninger per innbygger landet] + innb25 + bukst + innbhutd,",
              "        0",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Lønnsutgifter ekslusiv sosiale utgifter F201, F211 og F221",
            "expression": [
              "",
              "",
              "var lonnutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var pensj =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A090\")",
              ")",
              "",
              "var arbavg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "return (",
              "    lonnutg - pensj - arbavg",
              ")"
            ]
          },
          {
            "name": "TST BHG Brutto driftsutgifter eksklusiv avskrivninger",
            "expression": [
              "",
              "",
              "var brdrutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\")",
              ")",
              "",
              "var avs = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "return (",
              "    brdrutg - avs",
              ")"
            ]
          },
          {
            "name": "TST BHG Lønnsandel 1",
            "expression": [
              "",
              "ROUND(",
              "    DIVIDE([TST BHG Lønnsutgifter ekslusiv sosiale utgifter F201, F211 og F221], [TST BHG Brutto driftsutgifter eksklusiv avskrivninger]),",
              "    4",
              ")"
            ]
          },
          {
            "name": "TST BHG Lønn ekslusiv arbeidsgiveravgift",
            "expression": [
              "",
              "",
              "var lonnutg_f201 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var arbavg_f201 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "var lonnutg_f211 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var arbavg_f211 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "var lonnutg_f221 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var arbavg_f221 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "var f201 =",
              "lonnutg_f201 - arbavg_f201",
              "",
              "var f211 =",
              "lonnutg_f211 - arbavg_f211",
              "",
              "var f221 =",
              "lonnutg_f221 - arbavg_f221",
              "",
              "return (",
              "    f201 + f211 + f221",
              ")"
            ]
          },
          {
            "name": "TST BHG Lønnsandel 2",
            "expression": [
              "",
              "ROUND(",
              "    DIVIDE([TST BHG Lønn ekslusiv arbeidsgiveravgift], [TST BHG Brutto driftsutgifter eksklusiv avskrivninger]),",
              "    4",
              ")"
            ]
          },
          {
            "name": "TST BHG Lønnsutgiftsbehov pensjon",
            "expression": [
              "",
              "",
              "var ber_min_andel =",
              "[TST BHG Beregnet utgiftsbehov korrigert for forskjellene i inntektssystemet] *",
              "[Lønnsandel 1 landet]",
              "",
              "return (",
              "    ROUND(",
              "        ber_min_andel,",
              "        0",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Andel pensjon kommune",
            "expression": [
              "",
              "",
              "var pensj =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A090\")",
              ")",
              "",
              "var f201 =",
              "CALCULATE([Lønnsutgifter minus pensjonsinnskudd og arbeidsgiveravgift],",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\")",
              ")",
              "",
              "var f211 =",
              "CALCULATE([Lønnsutgifter minus pensjonsinnskudd og arbeidsgiveravgift],",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\")",
              ")",
              "",
              "var f221 =",
              "CALCULATE([Lønnsutgifter minus pensjonsinnskudd og arbeidsgiveravgift],",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\")",
              ")",
              "",
              "var nevner =",
              "f201 + f211 + f221",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(pensj, nevner),",
              "        4",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Andel arbeidsavgiveravgift kommune",
            "expression": [
              "",
              "",
              "var arbavg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "var lonnutg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var lonnutg_min_arbavg =",
              "lonnutg - arbavg",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(arbavg, lonnutg_min_arbavg),",
              "        4",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Innbyggertall pensjon",
            "expression": [
              "",
              "",
              "var lonnutg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var innb =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggertall per 1. juli\")",
              ")",
              "",
              "return (",
              "    IF(lonnutg < 100, 0, innb)",
              ")"
            ]
          },
          {
            "name": "TST BHG Andel utgiftsbehov kommuner med lønnsutgifter trinn 1",
            "expression": [
              "",
              "",
              "var r10 =",
              "[TST BHG Beregnet utgiftsbehov]",
              "",
              "var an10 =",
              "[TST BHG Innbyggertall pensjon]",
              "",
              "var an45 = ",
              "[Innbyggertall pensjon landet]",
              "",
              "var an10_d_an45 =",
              "ROUND(",
              "    DIVIDE(an10, an45),",
              "    4",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        r10 * an10_d_an45,",
              "        4",
              "    )",
              ")"
            ]
          },
          {
            "name": "TST BHG Andel utgiftsbehov kommuner med lønnsutgifter trinn 2",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var berutg =",
              "[TST BHG Beregnet utgiftsbehov]",
              "",
              "",
              "var sumasss = ",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE([TST BHG Andel utgiftsbehov kommuner med lønnsutgifter trinn 1],",
              "        FILTER(ALL(Region[ASSS kommune]), [ASSS kommune] = \"Ja\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var berutg_div_sumasss =",
              "DIVIDE(berutg, sumasss)",
              "",
              "return (",
              "    ROUND(",
              "       berutg_div_sumasss,",
              "       4",
              "    )",
              ")"
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ASSS Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>149</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>184</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Energitype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Energitype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Energitype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "ASSS kommune",
            "dataType": "string",
            "sourceColumn": "ASSS kommune"
          }
        ],
        "partitions": [
          {
            "name": "Region",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>170</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regionnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>153</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>135</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regionnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regionnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <int>153</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>135</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regionnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "isHidden": true,
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Energitypekode",
            "dataType": "string",
            "sourceColumn": "Energitypekode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Handsamingstidkode",
            "dataType": "string",
            "sourceColumn": "Handsamingstidkode"
          },
          {
            "name": "Konklusjonkode",
            "dataType": "string",
            "sourceColumn": "Konklusjonkode"
          },
          {
            "name": "Tiltakskategorikode",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorikode"
          },
          {
            "name": "Alderkode",
            "dataType": "string",
            "sourceColumn": "Alderkode"
          },
          {
            "name": "Omsorgs-/hjelpetiltakkode",
            "dataType": "string",
            "sourceColumn": "Omsorgs-/hjelpetiltakkode"
          },
          {
            "name": "Tjenestegrupperkode",
            "dataType": "string",
            "sourceColumn": "Tjenestegrupperkode"
          },
          {
            "name": "Utdanningkode",
            "dataType": "string",
            "sourceColumn": "Utdanningkode"
          },
          {
            "name": "Kommunal sektorkode",
            "dataType": "string",
            "sourceColumn": "Kommunal sektorkode"
          },
          {
            "name": "Postkode",
            "dataType": "string",
            "sourceColumn": "Postkode"
          },
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Avtaleformkode",
            "dataType": "string",
            "sourceColumn": "Avtaleformkode"
          },
          {
            "name": "Helsekontrollerkode",
            "dataType": "string",
            "sourceColumn": "Helsekontrollerkode"
          },
          {
            "name": "Eieformkode",
            "dataType": "string",
            "sourceColumn": "Eieformkode"
          },
          {
            "name": "Årstrinnkode",
            "dataType": "string",
            "sourceColumn": "Årstrinnkode"
          },
          {
            "name": "Eierforholdkode",
            "dataType": "string",
            "sourceColumn": "Eierforholdkode"
          },
          {
            "name": "Oppholdstidkode",
            "dataType": "string",
            "sourceColumn": "Oppholdstidkode"
          },
          {
            "name": "Kjønnkode",
            "dataType": "string",
            "sourceColumn": "Kjønnkode"
          },
          {
            "name": "Stillingstypekode",
            "dataType": "string",
            "sourceColumn": "Stillingstypekode"
          },
          {
            "name": "Kompetansekode",
            "dataType": "string",
            "sourceColumn": "Kompetansekode"
          },
          {
            "name": "Kildekode",
            "dataType": "string",
            "sourceColumn": "Kildekode"
          },
          {
            "name": "Tjenesteområdekode",
            "dataType": "string",
            "sourceColumn": "Tjenesteområdekode"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunal sektorkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunal sektorkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunal sektorkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          },
          {
            "name": "Netto driftsutgifter eksklusiv avskrivninger landet",
            "expression": [
              "",
              "",
              "var f201nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f201avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"201\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "var f211nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f211avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"211\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "var f221nd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\")",
              ")",
              "",
              "var f221avs =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"221\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "var nettominavs =",
              "(f201nd + f211nd + f221nd) - (f201avs + f211avs + f221avs)",
              "",
              "",
              "return (",
              "    nettominavs",
              ")"
            ]
          },
          {
            "name": "Netto driftsutgifter eksklusiv avskrivninger per innbygger landet",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var innbtall = ",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO02\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggertall per 1. juli\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var toto =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE([Netto driftsutgifter eksklusiv avskrivninger landet],",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    ) * 1000",
              ")",
              "",
              "return(",
              "    ROUND(",
              "        DIVIDE(toto, innbtall),",
              "        0",
              "    )",
              ")"
            ]
          },
          {
            "name": "Lønnsandel 1 landet",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var lonnutg =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE([Lønnsutgifter ekslusiv sosiale utgifter F201, F211 og F221 landet],",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "var brutdr = ",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE([Brutto driftsutgifter eksklusiv avskrivninger landet],",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar)",
              "    )",
              ")",
              "",
              "return(",
              "    ROUND(",
              "        DIVIDE(lonnutg, brutdr),",
              "        4",
              "    )",
              ")"
            ]
          },
          {
            "name": "Lønnsutgifter ekslusiv sosiale utgifter F201, F211 og F221 landet",
            "expression": [
              "",
              "",
              "var lonnutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var pensj =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A090\")",
              ")",
              "",
              "var arbavg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "return (",
              "    lonnutg - pensj - arbavg",
              ")"
            ]
          },
          {
            "name": "Brutto driftsutgifter eksklusiv avskrivninger landet",
            "expression": [
              "",
              "",
              "var brdrutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\")",
              ")",
              "",
              "var avs = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"201\",",
              "        \"211\",",
              "        \"221\"",
              "    }),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A590\")",
              ")",
              "",
              "return (",
              "    brdrutg - avs",
              ")"
            ]
          },
          {
            "name": "Lønnsutgifter minus pensjonsinnskudd og arbeidsgiveravgift",
            "expression": [
              "",
              "",
              "var lonnutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              ")",
              "",
              "var pensj =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A090\")",
              ")",
              "",
              "var arbavg =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"A099\")",
              ")",
              "",
              "return (",
              "    lonnutg - pensj - arbavg",
              ")"
            ]
          },
          {
            "name": "Innbyggertall pensjon landet",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var lonnutg =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar),",
              "        FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "           \"201\",",
              "            \"211\",",
              "            \"221\"",
              "        }),",
              "        FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AG16\")",
              "    )",
              ")",
              "",
              "var innb =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"ØKO02\"),",
              "        FILTER(ALL(Region[Kode]), [Kode] = \"0\"),",
              "        FILTER(ALL('År'[År]), [År] = valgte_aar),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggertall per 1. juli\")",
              "    )",
              ")",
              "",
              "return (",
              "    IF(lonnutg < 100, 0, innb)",
              ")"
            ]
          },
          {
            "name": "Andel utgiftsbehov kommuner med lønnsutgifter trinn 1 ASSS",
            "expression": [
              "",
              "",
              "var r10 =",
              "[TST BHG Beregnet utgiftsbehov]",
              "",
              "var an10 =",
              "[TST BHG Innbyggertall pensjon]",
              "",
              "var an45 = ",
              "[Innbyggertall pensjon landet]",
              "",
              "var an10_d_an45 =",
              "SUMX(",
              "    ALL('Alle Data'),",
              "    ROUND(",
              "        DIVIDE(an10, an45),",
              "        4",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        r10 * an10_d_an45,",
              "        4",
              "    )",
              ")"
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunal sektorkode</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunal sektorkode</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunal sektorkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Handsamingstid",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Handsamingstid",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Handsamingstid"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kilde",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kilde",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kilde"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Konklusjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Konklusjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Konklusjon].* FROM [dbo].[Konklusjon] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Konklusjon].* FROM [dbo].[Konklusjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Konklusjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Omsorgs-hjelpetiltak",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Omsorgs-hjelpetiltak",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Omsorgs-/hjelpetiltak"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Sammenslåtte Regioner",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "SammenslåingsDato",
            "dataType": "dateTime",
            "sourceColumn": "SammenslåingsDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Sammenslåtte Regioner",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sammenslåtte Regioner"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tiltakskategori",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tiltakskategori",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tiltakskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tjenestegrupper",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tjenestegrupper",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tjenestegrupper"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Utdanning",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Utdanning",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Utdanning"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kommunal sektor",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kommunal sektor",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kommunal sektor].* FROM [dbo].[Kommunal sektor] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kommunal sektor].* FROM [dbo].[Kommunal sektor] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kommunal sektor"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Post",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Post",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Post].* FROM [dbo].[Post] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Post].* FROM [dbo].[Post] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Post"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Regnskapsbegrep",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Regnskapsbegrep",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Regnskapsbegrep].* FROM [dbo].[Regnskapsbegrep] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Regnskapsbegrep].* FROM [dbo].[Regnskapsbegrep] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Regnskapsbegrep"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Avtaleform",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Avtaleform",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Avtaleform].* FROM [dbo].[Avtaleform] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Avtaleform].* FROM [dbo].[Avtaleform] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Avtaleform"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Helsekontroller",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Helsekontroller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Helsekontroller].* FROM [dbo].[Helsekontroller] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Helsekontroller].* FROM [dbo].[Helsekontroller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Helsekontroller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Eieform",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Eieform",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Eieform].* FROM [dbo].[Eieform] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eieform].* FROM [dbo].[Eieform] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eieform"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Årstrinn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Årstrinn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Årstrinn].* FROM [dbo].[Årstrinn] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Årstrinn].* FROM [dbo].[Årstrinn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Årstrinn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Eierforhold",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Eierforhold",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Eierforhold].* FROM [dbo].[Eierforhold] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eierforhold].* FROM [dbo].[Eierforhold] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eierforhold"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Oppholdstid",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Oppholdstid",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Oppholdstid].* FROM [dbo].[Oppholdstid] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Oppholdstid].* FROM [dbo].[Oppholdstid] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Oppholdstid"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kjønn",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kjønn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Stillingstype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Stillingstype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Stillingstype].* FROM [dbo].[Stillingstype] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Stillingstype].* FROM [dbo].[Stillingstype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Stillingstype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kompetanse",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kompetanse",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kompetanse].* FROM [dbo].[Kompetanse] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kompetanse].* FROM [dbo].[Kompetanse] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kompetanse"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tjenesteområde",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tjenesteområde",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tjenesteområde].* FROM [dbo].[Tjenesteområde] ",
              "dataSource": "KS-SQL2018;Reporting_Status"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tjenesteområde].* FROM [dbo].[Tjenesteområde] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tjenesteområde"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4e9f0201-a402-446a-8143-3524dec0a92e",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "e93c2126-b5fc-4246-b517-1d3e8d5fd7cc",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "7d2da773-d756-403e-b569-1ad00b2f5e9f",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "664363a3-aadb-4475-b62b-318ab1c5d07f",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "31871d8a-ff9e-49ed-be90-1776353945e4",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f6c09549-e3e3-4916-ad78-64e528b3bc32",
        "fromTable": "Alle Data",
        "fromColumn": "Energitypekode",
        "toTable": "Energitype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "594be1f1-a81a-452e-9716-b79eec7957c4",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cf2e5996-1feb-4ea4-8043-5ebfa5c19e6c",
        "fromTable": "Alle Data",
        "fromColumn": "Alderkode",
        "toTable": "Alder",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "dbf8b217-9570-4951-b6bd-b6e2b03b327f",
        "fromTable": "Alle Data",
        "fromColumn": "Handsamingstidkode",
        "toTable": "Handsamingstid",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f77ef936-3e3f-4d7b-afb8-c7e6f0894bc7",
        "fromTable": "Alle Data",
        "fromColumn": "Konklusjonkode",
        "toTable": "Konklusjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "aafab56c-d833-4f01-aa89-ebb84720ddbf",
        "fromTable": "Alle Data",
        "fromColumn": "Tiltakskategorikode",
        "toTable": "Tiltakskategori",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "086ee4f8-dbd1-498f-a83f-4ec576faba0c",
        "fromTable": "Alle Data",
        "fromColumn": "Omsorgs-/hjelpetiltakkode",
        "toTable": "Omsorgs-hjelpetiltak",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "29567bbc-14bb-407c-a300-bca620bf10db",
        "fromTable": "Alle Data",
        "fromColumn": "Tjenestegrupperkode",
        "toTable": "Tjenestegrupper",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "8697b357-b5df-4f45-9413-3a008fb72c1b",
        "fromTable": "Alle Data",
        "fromColumn": "Utdanningkode",
        "toTable": "Utdanning",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "1aeb7c2a-1a8c-4a67-92cb-aab607cbdcc1",
        "fromTable": "Alle Data",
        "fromColumn": "Kommunal sektorkode",
        "toTable": "Kommunal sektor",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "c2774a9c-4a71-445f-82fd-0a66bfa51217",
        "fromTable": "Alle Data",
        "fromColumn": "Postkode",
        "toTable": "Post",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "9550548b-1135-4ef0-9380-dccee1f29745",
        "fromTable": "Alle Data",
        "fromColumn": "Regnskapsbegrepkode",
        "toTable": "Regnskapsbegrep",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "5f3af89f-97a4-4064-862a-2b04ce06f490",
        "fromTable": "Alle Data",
        "fromColumn": "Avtaleformkode",
        "toTable": "Avtaleform",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "63d3461c-d0cc-4869-9286-1042448aa308",
        "fromTable": "Alle Data",
        "fromColumn": "Helsekontrollerkode",
        "toTable": "Helsekontroller",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "26b4adf3-a451-4e4c-a573-88a10519743d",
        "fromTable": "Alle Data",
        "fromColumn": "Eieformkode",
        "toTable": "Eieform",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "6cc46bd4-9520-4b76-af22-609cfef1acee",
        "fromTable": "Alle Data",
        "fromColumn": "Årstrinnkode",
        "toTable": "Årstrinn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "285b3b8f-65ad-4b65-bc8f-75d723c9155e",
        "fromTable": "Alle Data",
        "fromColumn": "Eierforholdkode",
        "toTable": "Eierforhold",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "73aff484-c54e-476a-a491-90df3c491c70",
        "fromTable": "Alle Data",
        "fromColumn": "Oppholdstidkode",
        "toTable": "Oppholdstid",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "a1b215cf-6e9d-4ccb-b872-8dc24f6057f6",
        "fromTable": "Alle Data",
        "fromColumn": "Kjønnkode",
        "toTable": "Kjønn",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "1ca1ad25-b741-40ea-914e-3bee214df7cc",
        "fromTable": "Alle Data",
        "fromColumn": "Stillingstypekode",
        "toTable": "Stillingstype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "bb559025-e9cd-4208-8e4b-c82e20d74341",
        "fromTable": "Alle Data",
        "fromColumn": "Kompetansekode",
        "toTable": "Kompetanse",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "a79ebd02-84d3-4db8-8a07-6ebc1e49ff77",
        "fromTable": "Alle Data",
        "fromColumn": "Tjenesteområdekode",
        "toTable": "Tjenesteområde",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "98e754fa-6904-41f5-b1fb-7b1a5d14a0dc",
        "fromTable": "Alle Data",
        "fromColumn": "Kildekode",
        "toTable": "Kilde",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}