{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/KS-SQL2018;Reporting_Status",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "KS-SQL2018",
            "database": "Reporting_Status"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "ks-sql2018;Reporting_Status",
          "Username": "Axel.Hjelmervik.Hansen@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori"
          },
          {
            "name": "ASSS kommune",
            "dataType": "string",
            "sourceColumn": "ASSS kommune"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Status Kommune Indikatorer",
        "columns": [
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Attraktive arbeidsgivere",
            "dataType": "int64",
            "sourceColumn": "Attraktive arbeidsgivere"
          },
          {
            "name": "Attraktive byer og steder",
            "dataType": "int64",
            "sourceColumn": "Attraktive byer og steder"
          },
          {
            "name": "Deltagende innbyggere",
            "dataType": "int64",
            "sourceColumn": "Deltagende innbyggere"
          },
          {
            "name": "Effektive og innovative",
            "dataType": "int64",
            "sourceColumn": "Effektive og innovative"
          },
          {
            "name": "Klima og miljøvennlig utvikling",
            "dataType": "int64",
            "sourceColumn": "Klima og miljøvennlig utvikling"
          },
          {
            "name": "Konkurranse næringsliv",
            "dataType": "int64",
            "sourceColumn": "Konkurranse næringsliv"
          },
          {
            "name": "God oppvekst og godt liv",
            "dataType": "int64",
            "sourceColumn": "God oppvekst og godt liv"
          },
          {
            "name": "Mangfold og inkludering",
            "dataType": "int64",
            "sourceColumn": "Mangfold og inkludering"
          },
          {
            "name": "Selvstendige",
            "dataType": "int64",
            "sourceColumn": "Selvstendige"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    #\"dbo_Status Kommune Indikatorer\" = Source{[Schema=\"dbo\",Item=\"Status Kommune Indikatorer\"]}[Data]",
                "in",
                "    #\"dbo_Status Kommune Indikatorer\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Båtruter",
            "expression": [
              "",
              "",
              "/* Millioner passasjerkilometer buss, båt, t-bane, trikk/bybane - fylkeskommunale ruter*/",
              "",
              "var ant_btrut =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11844\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Passasjer, båtruter (antall)\")",
              ")",
              "",
              "var btrut_1mill =",
              "DIVIDE(ant_btrut, 1000000)",
              "",
              "return (",
              "    ROUND(",
              "        btrut_1mill,",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Buss",
            "expression": [
              "",
              "",
              "/* Millioner passasjerkilometer buss, båt, t-bane, trikk/bybane - fylkeskommunale ruter*/",
              "",
              "var ant_buss =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11844\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Passasjerer, buss (antall)\")",
              ")",
              "",
              "var buss_1mill =",
              "DIVIDE(ant_buss, 1000000)",
              "",
              "return (",
              "    ROUND(",
              "        buss_1mill,",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "T-bane og trikk/bybane",
            "expression": [
              "",
              "",
              "/* Millioner passasjerkilometer buss, båt, t-bane, trikk/bybane - fylkeskommunale ruter*/",
              "",
              "var ant_baner =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11844\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Passasjerer, t-bane og trikk/bybane (antall)\")",
              ")",
              "",
              "var baner_1mill =",
              "DIVIDE(ant_baner, 1000000)",
              "",
              "return (",
              "    ROUND(",
              "        baner_1mill,",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Omdisponering til andre formål enn landbruk i alt",
            "expression": [
              "",
              "",
              "/* Dekar dyrka og dyrkbar jord som er omdisponert til andre formål enn landbruk */",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"07903\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Omdisponering til andre formål enn landbruk i alt\"",
              "    )",
              ")"
            ]
          },
          {
            "name": "Dyrka jord",
            "expression": [
              "",
              "",
              "/* Dekar dyrka og dyrkbar jord som er omdisponert til andre formål enn landbruk */",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"07903\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Dyrka jord\"",
              "    )",
              ")"
            ]
          },
          {
            "name": "Dyrkbar jord",
            "expression": [
              "",
              "",
              "/* Dekar dyrka og dyrkbar jord som er omdisponert til andre formål enn landbruk */",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"07903\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Dyrkbar jord\"",
              "    )",
              ")"
            ]
          }
        ]
      },
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kode"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Variabel"
          },
          {
            "name": "År",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "År"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      },
      {
        "name": "Formål",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/KS-SQL2018;Reporting_Status\",",
                "    dbo_Formål = Source{[Schema=\"dbo\",Item=\"Formål\"]}[Data]",
                "in",
                "    dbo_Formål"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fd45f95f-1458-41de-94d2-adbfedaf54d1",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "eed6dfec-a469-473b-83d0-e397180a58be",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "9989dbda-0a8f-4ca3-abc2-d8a4cf13a03f",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "f775df9d-0345-47e7-a6ec-9152a6c368f3",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}